export const L_STATIONS = [
  { id: "8-av", label: "8 Av" },
  { id: "6-av", label: "6 Av" },
  { id: "14-st-union-sq", label: "14 St–Union Sq" },
  { id: "3-av", label: "3 Av" },
  { id: "1-av", label: "1 Av" },
  { id: "bedford-av", label: "Bedford Av" },
  { id: "lorimer-st", label: "Lorimer St" },
  { id: "graham-av", label: "Graham Av" },
  { id: "grand-st", label: "Grand St" },
  { id: "montrose-av", label: "Montrose Av" },
  { id: "morgan-av", label: "Morgan Av" },
  { id: "jefferson-st", label: "Jefferson St" },
  { id: "dekalb-av", label: "DeKalb Av" },
  { id: "myrtle-wyckoff", label: "Myrtle–Wyckoff Avs" },
  { id: "halsey-st", label: "Halsey St" },
  { id: "wilson-av", label: "Wilson Av" },
  { id: "bushwick-av", label: "Bushwick Av–Aberdeen St" },
  { id: "broadway-jn", label: "Broadway Junction" },
  { id: "atlantic-av", label: "Atlantic Av" },
  { id: "sutter-av", label: "Sutter Av" },
  { id: "livonia-av", label: "Livonia Av" },
  { id: "new-lots-av", label: "New Lots Av" },
  { id: "east-105-st", label: "East 105 St" },
  { id: "canarsie", label: "Canarsie–Rockaway Pkwy" },
] as const
